services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    environment:
      USER: postgres
      NAME: postgres
      HOST: db
      PORT: 5432
      USE_S3: "TRUE"
      DEBUG: "FALSE"
    depends_on:
      - db
    command: sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --clear --noinput &&
      python manage.py loaddata
      fixtures/aircraft.json
      fixtures/airports.json
      fixtures/blog.json
      fixtures/flights.json &&
      python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
