# Generated by Django 4.2.3 on 2023-07-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_airport_iata"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="outbound_date",
            field=models.DateField(default="2023-08-13"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flight",
            name="arr_time",
            field=models.TimeField(verbose_name="Arrival time"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="dep_time",
            field=models.TimeField(verbose_name="Departure time"),
        ),
    ]
