# Generated by Django 4.2.3 on 2023-07-17 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_flight_outbound_date_alter_flight_arr_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Flight number must be in the format UX000",
                        regex="UX\\d\\d\\d",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
