# Generated by Django 4.2.3 on 2023-08-01 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_flight_flight_number_alter_flight_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Flight number must be in the format UX0000",
                        regex="UX\\d\\d\\d\\d",
                    )
                ],
            ),
        ),
    ]
