# Generated by Django 4.2.3 on 2023-08-06 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
    ]
