# Generated by Django 4.2.3 on 2023-08-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                ("cover_image", models.ImageField(upload_to="blog_images/")),
            ],
        ),
    ]
