# Generated by Django 4.2.3 on 2023-08-18 21:09

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="content_rendered",
            field=markdownfield.models.RenderedMarkdownField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=markdownfield.models.MarkdownField(rendered_field="content_rendered"),
        ),
    ]
